check if tags was fetched

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -37,9 +37,15 @@ jobs:
           TOKEN=$(curl "https://auth.docker.io/token?service=registry.docker.io&scope=repository:ixsystems/${{ matrix.containers.app }}:pull" | jq '.token' --raw-output)
 
           # Check if the "production" version already exists in dokerhub
-          # FIXME: if auhtorization fails, this will think the tag does not exist
-          EXISTS=$(curl -H "Authorization: Bearer $TOKEN" "https://index.docker.io/v2/ixsystems/${{ matrix.containers.app }}/tags/list" \
-            | jq --arg version "$VERSION" '.tags | index($version) != null')
+          TAGS=$(curl -H "Authorization: Bearer $TOKEN" "https://index.docker.io/v2/ixsystems/${{ matrix.containers.app }}/tags/list"
+
+          if echo "$TAGS" | grep -q "errors"; then
+            echo "Failed to get tags from dockerhub"
+            echo "$TAGS"
+            exit 1
+          fi
+
+          EXISTS=$(echo "$TAGS" | jq --arg version "$VERSION" '.tags | index($version) != null')
 
           # If the version already exists, fail fast
           if [[ $EXISTS == "true" ]]; then
